### ISSUE TITLE
Typescript type defs

### ISSUE THREAD

**Issue by kennetpostigo** [jaydenseric/extract-files#12]
Hey there!

Been using this project recently (love it), but I wanted to ask if there is any chance there might type definitions for this library?

I couldn't find any in DefinitelyTyped, so not sure if maybe someone from the community might see this that maybe rolled their own or if maybe you had this in the works.

**Comment by jaydenseric** [comment]
Sorry to leave you hanging, the notification slipped through the cracks!

Thanks for the kind words man  :)

I don't use TypeScript myself so I'm not sure where the best place is to get the types, although it's surprising none are on DefinitelyTyped yet. Maybe you could put them up?

> or if maybe you had this in the works

No, there are no plans to add types beyond JSDoc for documentation purposes in this repo.

**Comment by jaydenseric** [comment]
Duplicates https://github.com/jaydenseric/extract-files/issues/7 , which has been reopened.
