### ISSUE TITLE
"No valid exports main found for ..." Error on node 13.3.0

### ISSUE THREAD

**Issue by A-Kasaaian** [jaydenseric/extract-files#13]
Error: No valid exports main found for '.../node_modules/extract-files'

This error comes up when I install apollo-upload-client and use this package in an SSR project with Nodjs v13.3.0

**Comment by jaydenseric** [comment]
Could you please try it with the latest Node.js v12 or v13 version?

This package uses the final [Node.js conditional `exports` API](https://nodejs.org/api/esm.html#esm_conditional_exports):

https://github.com/jaydenseric/extract-files/blob/v8.0.0/package.json#L34

**Comment by jaydenseric** [comment]
Node.js v13.0.0 - v13.6 will not work as those versions support package `exports` but not conditional `exports`. 

You can get v13.2 - v13.6 to work with the Node.js `--experimental-conditional-exports` flag.

Node.js v13.7+ will work fine, and all v10 and v12 versions should work.

I just updated the package `engines.node` to clarify that supported Node.js versions are `10 - 12 || >= 13.7`, which is released in [v8.1.0](https://github.com/jaydenseric/extract-files/releases/tag/v8.1.0).

**Comment by A-Kasaaian** [comment]
Thanks. Yea, last night I downgraded Node to 12.16.1 and it worked. I upgraded it to 13.12.0 now and it works too. Cool :)

**Comment by sarahannnicholson** [comment]
Brilliant! I happened to be in the unsupported range with node v13.6.0

Ugraded to 13.12.0 as per the above comments from @jaydenseric  and @A-Kasaaian . Works great :)
