### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by dgomez-orangeloops** [jaydenseric/extract-files#15]
CRA with webpack config:

_Module not found: Error: Can't resolve 'extract-files/public/ReactNativeFile'
Module not found: Error: Can't resolve 'extract-files/public/extractFiles'
Module not found: Error: Can't resolve 'extract-files/public/isExtractableFile'_

Please, review this issue: https://github.com/jaydenseric/apollo-upload-client/issues/230#issuecomment-709677574 

thanks!

**Comment by jaydenseric** [comment]
I think you have it the other way around, you should raise an issue with `webpack` about `extract-files` support. The burden is on them to be able to resolve standard Node.js packages that Node.js itself is able to resolve just fine:

<img width="1007" alt="Screen Shot 2020-10-16 at 12 58 32 pm" src="https://user-images.githubusercontent.com/1754873/96204246-96491f00-0faf-11eb-828b-7e57db1d0524.png">

**Comment by jaydenseric** [comment]
Also, I'm a little confused by your issue title `Webpack 5 support` when in the description you say `CRA with webpack config` – CRA doesn't use webpack v5 yet.
