### ISSUE TITLE
Package "extract-files" exists but package.json "exports" does not include entry for "./public/extractFiles"

### ISSUE THREAD

**Issue by opusmagnum** [jaydenseric/extract-files#18]
Hi, 

```shell
 npx snowpack dev --polyfill-node
...
[22:24:01] [snowpack] Package "extract-files" exists but package.json "exports" does not include entry for "./public/extractFiles".
```
The recommendation from Snowpack common errors page -- 
[Package exists but package.json “exports” does not include entry](https://www.snowpack.dev/reference/common-error-details#package-exists-but-package.json-%E2%80%9Cexports%E2%80%9D-does-not-include-entry) :

> If you see this error message, that means that you’ve imported a file path not allowed in the export map. If you believe this to be an error, reach out to the package author to request the file be added to their export map.

In my yarn.lock:
```yaml
apollo-upload-client@^14.1.3:
...
  dependencies:
    ...
    extract-files "^9.0.0"
```
Node version: v14.16.1
Snowpack version: 3.3.6

Thanks in advance,
Alexander

**Comment by jaydenseric** [comment]
See https://github.com/jaydenseric/apollo-upload-client/issues/257#issuecomment-826535257 . Hopefully issues like this will be resolved soon when I publish everything.

**Comment by jaydenseric** [comment]
Please check everything works ok now that `extract-files` [v10](https://github.com/jaydenseric/extract-files/releases/tag/v10.0.0) has been published, along with `apollo-upload-client` [v15](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v15.0.0) (if that's how you were using it) 🙏
