### ISSUE TITLE
imports are broken for @urql/exchange-multipart-fetch

### ISSUE THREAD

**Issue by PhilippMolitor** [jaydenseric/extract-files#21]
`@urql/echange-multipart-fetch` has upgraded the `extract-files` package from version `^8.1.0` to `^11.0.0`, which broke an import/export:

```
yarn run v1.22.11
$ craco build
Creating an optimized production build...
Failed to compile.

/Users/phil/Projects/***redacted***/node_modules/@urql/exchange-multipart-fetch/node_modules/extract-files/public/index.mjs
"export 'default' (reexported as 'ReactNativeFile') was not found in './ReactNativeFile.js'
```

Version `0.1.12` of `@urql/echange-multipart-fetch` works fine, `0.1.13` breaks my build process ( `create-react-app` ).

See: https://github.com/FormidableLabs/urql/pull/1795

**Comment by jaydenseric** [comment]
Your issue is with `create-react-app` not bundling correctly, please look for or file an issue there. You can verify that Node.js can import the module just fine…

In `test.mjs`:

```js
import { ReactNativeFile } from 'extract-files';

// Or:
// import ReactNativeFile from 'extract-files/public/ReactNativeFile.js';

console.log(ReactNativeFile);
```

Then run `node test.mjs`.

It's on CRA to ensure perfectly valid Node.js package bundle correctly.
