### ISSUE TITLE
Error: Deprecation warning in build

### ISSUE THREAD

**Issue by w3bdesign** [jaydenseric/extract-files#23]
error (node:3643) [DEP0148]
DeprecationWarning: Use of deprecated folder mapping "./public/" in the "exports" field module resolution of the package at /opt/build/repo/node_modules/extract-files/package.json

**Comment by jaydenseric** [comment]
That has been fixed for some time; you must be using an old version of `extract-files`. Update and you won't see that deprecation warning.

Here is the updated `exports` field:

https://github.com/jaydenseric/extract-files/blob/6d8f725e9b9973fd564bfdd784cd9b2ff58f8470/package.json#L37

Which is definitely published:

https://unpkg.com/extract-files@11.0.0/package.json
