### ISSUE TITLE
Deprecation Warning 

### ISSUE THREAD

**Issue by janedzumerko** [jaydenseric/extract-files#24]
Hi, I am using gatsby v4 and when running my project I am getting this error.
```
[DEP0148] DeprecationWarning: Use of deprecated folder mapping
 "./public/" in the "exports" field module resolution of the package at
/Users/.../my-gatsby-project/node_modules/extract-file
s/package.json.

```

I believe it's coming from this module, which I don't use directly, but through some other module. Can I somehow fix the error in my repo, or it should be done in this repo ?

**Comment by jaydenseric** [comment]
With the current version of `extract-files` you won't get a deprecation warning:

https://github.com/jaydenseric/extract-files/blob/v11.0.0/package.json#L37

One of your dependencies has an out of date dependency on `extract-files`; you can run `npm ls extract-files` to figure out which one.
