### ISSUE TITLE
Don't modify original input

### ISSUE THREAD

**Issue by juona** [jaydenseric/extract-files#8]
Hey there again!

One more from me, and this time it's a client issue : ] not necessarily a bug, more like asking for opinion.

Your extract-files module traverses the whole GraphQL request looking for files/blobs. Once found these files/blobs are pushed into the upload request while the nodes which contained them are updated with null values. I don't fully understand this but it seems like this is done so that later in the server these nodes can be "reconstructed", i.e. Upload types are inserted where Files were on the client side.

Pseudo example.

Assume that our form data looks like this:

```
input: {
    description: "Some text",
    mainPhoto: File<whatever is inside the file>
}
```

After `extractFiles(body)` it looks like this:

```
input: {
    description: "Some text",
    mainPhoto: null
}
```

The problem is that the request input object is modified directly and if the request fails, this input is no longer valid as it no longer has the files/blobs in it. So if the user tries to resubmit the same request, it won't work.

Since most of today's front-end frameworks work based on two-way binding between inputs and form data, this means that I have lost the files that I have selected for input. This then suggests that the simplest way to work around this would be always submitting a deep copy of the form data rather than passing it directly into the mutation, which is somewhat unusual/unnecessary.

Furthermore, creating deep copies of the form data is not exactly a viable solution either, since it is impossible to copy a File object. One needs to explicitly instantiate copy instances of File object for each and every file that's being uploaded.

Hope my explanation is clear. What are your thoughts on this? Is there a way to perhaps create a copy of the input that you receive and work on the copy while leaving the original reference intact?

Keep up the good work! : ]

**Comment by jaydenseric** [comment]
This is a good idea, has been discussed before here: https://github.com/jaydenseric/apollo-upload-client/issues/81#issuecomment-376025464

**Comment by juona** [comment]
Understood, thank you for the details : ]
